# Generated by Django 5.1.4 on 2025-03-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=50, unique=True)),
                ('customerName', models.CharField(max_length=255)),
                ('jobType', models.IntegerField(choices=[(1, 'Type 1'), (2, 'Type 2')])),
                ('customerPhone', models.CharField(max_length=15)),
                ('queueTime', models.DateTimeField(auto_now_add=True)),
                ('scheduledTime', models.DateTimeField()),
                ('messageSent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.customerqueue')),
            ],
        ),
    ]
